a.out : main.o
	g++ main.o
	rm *.o

main.o : main.cpp
	g++ -c main.cpp

lamp.o : lamp.cpp lamp.hpp
	g++ -c lamp.cpp lamp.hpp

ButtonImplementation.o : ButtonImplementation.cpp ButtonImplementation.hpp
	g++ -c ButtonImplementation.cpp ButtonImplementation.hpp
